import { randomBytes } from "node:crypto";
import type Database from "better-sqlite3";

/**
 * Per-court scorer tokens. A scorer opens /livescore/:court?token=... and can
 * ONLY score that court (+1/-1). The token is generated by the admin flow
 * (match start) and validated on the scoring routes. This gives volunteers a
 * scoped, no-login way to score one court without any other access.
 */
interface Row {
  court_id: number;
  token: string;
  created_at: number;
}

export class ScorerTokenStore {
  private readonly db: Database.Database;

  constructor(db: Database.Database) {
    this.db = db;
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS scorer_token (
        court_id   INTEGER PRIMARY KEY,
        token      TEXT NOT NULL,
        created_at INTEGER NOT NULL
      );
    `);
  }

  /** The current token for a court, or undefined if none issued. */
  get(courtId: number): string | undefined {
    const row = this.db
      .prepare(`SELECT token FROM scorer_token WHERE court_id = ?`)
      .get(courtId) as Pick<Row, "token"> | undefined;
    return row?.token;
  }

  /** Get the existing token or create+persist a new one for the court. */
  ensure(courtId: number, now = Date.now()): string {
    const existing = this.get(courtId);
    if (existing) return existing;
    const token = randomBytes(16).toString("hex");
    this.db
      .prepare(
        `INSERT INTO scorer_token (court_id, token, created_at) VALUES (?, ?, ?)`,
      )
      .run(courtId, token, now);
    return token;
  }

  /** Force a new token (invalidates any old link). */
  rotate(courtId: number, now = Date.now()): string {
    const token = randomBytes(16).toString("hex");
    this.db
      .prepare(
        `INSERT INTO scorer_token (court_id, token, created_at)
         VALUES (?, ?, ?)
         ON CONFLICT(court_id) DO UPDATE SET token = excluded.token, created_at = excluded.created_at`,
      )
      .run(courtId, token, now);
    return token;
  }

  /** Validate a token for a court (constant-ish comparison). */
  isValid(courtId: number, token: string | undefined): boolean {
    if (!token) return false;
    const current = this.get(courtId);
    return Boolean(current) && current === token;
  }

  clear(courtId: number): void {
    this.db.prepare(`DELETE FROM scorer_token WHERE court_id = ?`).run(courtId);
  }
}
